# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160612_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='content',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='File',
            new_name='title',
        ),
    ]
